name: Scheduled health check

on:
  schedule:
    - cron: '* * * * *'

jobs:
  check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://patientor2.azurewebsites.net
